// 'use client'
// import type { Metadata } from 'next'
// import 'bootstrap/dist/css/bootstrap.min.css';
// import './globals.css'
// import NavbarPrimary from '@/components/navbars/Navbars';
// import NavbarAfter from '@/components/navbars/NavbarsAfter';
// import React, { useState } from 'react';

// // export const metadata: Metadata = {
// //   title: 'Cinema Online',
// //   description: 'Cinema Online, destinasi utama Anda untuk mengeksplorasi dunia hiburan sinematik secara digital. Dengan tampilan yang elegan dan antarmuka yang ramah pengguna, kami berkomitmen untuk memberikan pengalaman menonton film yang tak tertandingi di kenyamanan rumah Anda.',
// // }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   const [isLoggedIn, setIsLoggedIn] = useState(false);
//   return (
//     <html lang="id">
//       <body>
//        {isLoggedIn ? <NavbarAfter/>:<NavbarPrimary setIsLoggedIn={setIsLoggedIn}/>}
//         {children}
//       </body>
//     </html>
//   )
// }

// 'use client'
// import type { Metadata } from 'next'
// import 'bootstrap/dist/css/bootstrap.min.css';
// import './globals.css'
// import NavbarPrimary from '@/components/navbars/Navbars';
// import NavbarAfter from '@/components/navbars/NavbarsAfter';
// import React, { useState } from 'react';

// // export const metadata: Metadata = {
// //   title: 'Cinema Online',
// //   description: 'Cinema Online, destinasi utama Anda untuk mengeksplorasi dunia hiburan sinematik secara digital. Dengan tampilan yang elegan dan antarmuka yang ramah pengguna, kami berkomitmen untuk memberikan pengalaman menonton film yang tak tertandingi di kenyamanan rumah Anda.',
// // }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   const [isLoggedIn, setIsLoggedIn] = useState(false);
//   return (
//     <html lang="id">
//       <body>
//        {isLoggedIn ? <NavbarAfter/>:<NavbarPrimary setIsLoggedIn={setIsLoggedIn}/>}
//         {children}
//       </body>
//     </html>
//   )
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import App from "./app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App>
          {children}
        </App>
          
      </body>
    </html>
  );
}
