// 'use client'
// import type { Metadata } from 'next'
// import 'bootstrap/dist/css/bootstrap.min.css';
// import './globals.css'
// import NavbarPrimary from '@/components/navbars/Navbars';
// import { useState } from 'react';

// export const metadata: Metadata = {
//   title: 'Cinema Online',
//   description: 'Cinema Online, destinasi utama Anda untuk mengeksplorasi dunia hiburan sinematik secara digital. Dengan tampilan yang elegan dan antarmuka yang ramah pengguna, kami berkomitmen untuk memberikan pengalaman menonton film yang tak tertandingi di kenyamanan rumah Anda.',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   const [loggedIn, setLoggedIn] = useState(false);
//   return (
//     <html lang="id">
//       <body>
//         <NavbarPrimary  loggedId={loggedIn} setLoggedId={setLoggedIn}/>
//         {children}
//       </body>
//     </html>
//   )
// }

import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'


export const metadata: Metadata = {
  title: 'Cinema Online',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
